import Link from "next/link";

export default function AboutPage() {
  return (
    <div className="min-h-screen bg-[#08090e] text-white">
      <nav className="flex items-center justify-between px-8 py-4 border-b border-white/[0.06]">
        <Link href="/" className="flex items-center gap-2">
          <div className="w-5 h-5 rounded bg-gradient-to-br from-indigo-500 to-purple-500" />
          <span className="text-sm font-bold text-zinc-100 tracking-tight">Atticus</span>
        </Link>
        <div className="flex gap-4">
          <Link href="/terms" className="text-xs text-zinc-400 hover:text-zinc-200">Terms</Link>
          <Link href="/privacy" className="text-xs text-zinc-400 hover:text-zinc-200">Privacy</Link>
        </div>
      </nav>

      <main className="max-w-2xl mx-auto px-8 py-16">
        <h1 className="text-4xl font-extrabold text-white mb-4 tracking-tight">About Atticus</h1>
        <p className="text-sm text-indigo-300 mb-8">Legal Research Intelligence</p>

        <div className="space-y-6 text-sm text-zinc-400 leading-relaxed">
          <p>
            Atticus is an AI-powered legal research platform built for small and mid-size legal teams
            who need research-grade answers without an enterprise price tag.
          </p>
          <p>
            Upload your case files — contracts, filings, transcripts, NDAs — and ask questions in
            plain English. Atticus reads the documents, retrieves the most relevant passages through
            a hybrid search pipeline, and returns structured answers with exact page citations.
          </p>

          <div className="border-t border-white/[0.06] pt-6">
            <h2 className="text-base font-bold text-white mb-3">What Atticus does</h2>
            <ul className="space-y-2 list-disc list-inside text-zinc-500">
              <li>Cited answers from your uploaded documents, not from the web</li>
              <li>Risk flag detection for contracts (liability, IP, non-compete clauses)</li>
              <li>Case organization — group documents into named matters</li>
              <li>Team discussion boards for sharing findings with colleagues</li>
              <li>Usage analytics and cost transparency</li>
            </ul>
          </div>

          <div className="border-t border-white/[0.06] pt-6">
            <h2 className="text-base font-bold text-white mb-3">What Atticus does not do</h2>
            <ul className="space-y-2 list-disc list-inside text-zinc-500">
              <li>Provide legal advice — all AI outputs are research aids only</li>
              <li>Access external legal databases (Westlaw, LexisNexis)</li>
              <li>Replace attorney judgment or replace an attorney-client relationship</li>
            </ul>
          </div>

          <div className="border-t border-white/[0.06] pt-6">
            <h2 className="text-base font-bold text-white mb-3">Technology</h2>
            <p>
              Atticus uses an 8-stage hybrid retrieval pipeline combining dense vector search
              (pgvector) with BM25 keyword search and cross-encoder reranking. Documents are parsed
              with OCR support for scanned PDFs. Answers are generated by Claude (Anthropic) with
              structured citations.
            </p>
          </div>

          <div className="border-t border-white/[0.06] pt-6">
            <h2 className="text-base font-bold text-white mb-3">Data privacy</h2>
            <p>
              Your documents are stored securely and are only used to answer your queries. They are
              never used to train AI models. Documents are deleted on request (GDPR Art. 17).
            </p>
          </div>
        </div>

        <div className="mt-12 pt-8 border-t border-white/[0.06]">
          <Link
            href="/"
            className="text-sm text-indigo-300 hover:text-indigo-200 transition-colors"
          >
            ← Back to home
          </Link>
        </div>
      </main>
    </div>
  );
}
