"""Firebase Authentication for Atticus.

Flow:
  1. User enters email + password (or registers).
  2. We POST to Firebase Auth REST API → get an ID token.
  3. Token stored in st.session_state — valid for 1 hour.
  4. On expiry the login screen reappears automatically.
  5. Every database query is scoped to the authenticated user_id (Firebase UID).

Setup (one-time):
  1. Create a Firebase project at https://console.firebase.google.com
  2. Enable Email/Password sign-in under Authentication → Sign-in method
  3. Download the service account JSON → save as firebase-service-account.json
     (add to .gitignore — it's a secret)
  4. Set FIREBASE_WEB_API_KEY in your .env (from Project Settings → General)
  5. Set FIREBASE_SERVICE_ACCOUNT_PATH=firebase-service-account.json in .env
"""
from __future__ import annotations

import json
import os
from pathlib import Path
from urllib.parse import urlencode

import requests
import streamlit as st

_FIREBASE_AUTH_URL = "https://identitytoolkit.googleapis.com/v1/accounts"


# ── Helpers ────────────────────────────────────────────────────────────────────

def _web_api_key() -> str:
    key = os.getenv("FIREBASE_WEB_API_KEY") or os.getenv("FIREBASE_API_KEY", "")
    if not key:
        raise RuntimeError(
            "FIREBASE_API_KEY not set. Add it to your .env file.\n"
            "Find it at: Firebase Console → Project Settings → General → Web API Key"
        )
    return key


def _firebase_post(endpoint: str, payload: dict) -> dict:
    """POST to Firebase Auth REST API. Returns the JSON response."""
    url = f"{_FIREBASE_AUTH_URL}:{endpoint}?key={_web_api_key()}"
    resp = requests.post(url, json=payload, timeout=10)
    data = resp.json()
    if not resp.ok:
        error_msg = data.get("error", {}).get("message", "Unknown Firebase error")
        raise AuthError(_friendly_error(error_msg))
    return data


def _friendly_error(firebase_msg: str) -> str:
    mapping = {
        "EMAIL_NOT_FOUND":        "No account found with that email address.",
        "INVALID_PASSWORD":       "Incorrect password.",
        "INVALID_EMAIL":          "Invalid email address.",
        "USER_DISABLED":          "This account has been disabled.",
        "EMAIL_EXISTS":           "An account with this email already exists.",
        "WEAK_PASSWORD":          "Password must be at least 6 characters.",
        "TOO_MANY_ATTEMPTS_TRY_LATER": "Too many failed attempts. Please wait and try again.",
        "INVALID_LOGIN_CREDENTIALS": "Invalid email or password.",
    }
    for key, msg in mapping.items():
        if key in firebase_msg:
            return msg
    return "Authentication failed. Please try again."


# ── Public API ─────────────────────────────────────────────────────────────────

class AuthError(Exception):
    """Raised on authentication failures — message is safe to show the user."""


def sign_in(email: str, password: str) -> dict:
    """Sign in with email and password. Returns the Firebase user dict."""
    data = _firebase_post("signInWithPassword", {
        "email": email.strip().lower(),
        "password": password,
        "returnSecureToken": True,
    })
    return {
        "uid":          data["localId"],
        "email":        data["email"],
        "display_name": data.get("displayName", email.split("@")[0]),
        "id_token":     data["idToken"],
        "refresh_token": data["refreshToken"],
    }


def register(email: str, password: str, display_name: str = "") -> dict:
    """Register a new user. Returns the Firebase user dict."""
    data = _firebase_post("signUp", {
        "email": email.strip().lower(),
        "password": password,
        "returnSecureToken": True,
    })
    user = {
        "uid":          data["localId"],
        "email":        data["email"],
        "display_name": display_name or email.split("@")[0],
        "id_token":     data["idToken"],
        "refresh_token": data["refreshToken"],
    }
    # Set display name if provided
    if display_name:
        try:
            _firebase_post("update", {
                "idToken": data["idToken"],
                "displayName": display_name,
                "returnSecureToken": False,
            })
        except Exception:
            pass  # Non-critical — name can be set later in profile
    return user


def create_google_auth_uri(continue_uri: str, identifier: str = "") -> str:
    """Return a Google OAuth URL generated by Firebase Auth."""
    payload = {
        "providerId": "google.com",
        "continueUri": continue_uri,
        "identifier": identifier or "user@example.com",
    }
    data = _firebase_post("createAuthUri", payload)
    auth_uri = data.get("authUri")
    if not auth_uri:
        raise AuthError("Google Sign-In is not configured for this Firebase project.")
    return auth_uri


def sign_in_with_google_id_token(id_token: str, request_uri: str) -> dict:
    """Sign in to Firebase using a Google ID token returned by OAuth."""
    post_body = urlencode({
        "id_token": id_token,
        "providerId": "google.com",
    })
    data = _firebase_post("signInWithIdp", {
        "postBody": post_body,
        "requestUri": request_uri,
        "returnIdpCredential": True,
        "returnSecureToken": True,
    })
    email = data.get("email", "")
    return {
        "uid":           data["localId"],
        "email":         email,
        "display_name":  data.get("displayName") or (email.split("@")[0] if email else "User"),
        "id_token":      data["idToken"],
        "refresh_token": data["refreshToken"],
    }


def refresh_token(refresh_token_str: str) -> dict | None:
    """Exchange a refresh token for a fresh ID token. Returns None on failure."""
    url = f"https://securetoken.googleapis.com/v1/token?key={_web_api_key()}"
    try:
        resp = requests.post(url, json={
            "grant_type": "refresh_token",
            "refresh_token": refresh_token_str,
        }, timeout=10)
        if resp.ok:
            data = resp.json()
            return {
                "id_token":     data["id_token"],
                "refresh_token": data["refresh_token"],
            }
    except Exception:
        pass
    return None


def send_password_reset(email: str) -> None:
    """Send a password reset email."""
    _firebase_post("sendOobCode", {
        "requestType": "PASSWORD_RESET",
        "email": email.strip().lower(),
    })


def send_email_verification(id_token: str) -> None:
    """Send an email verification link to the signed-in user."""
    try:
        _firebase_post("sendOobCode", {
            "requestType": "VERIFY_EMAIL",
            "idToken": id_token,
        })
    except Exception:
        pass  # non-critical — user can request again from profile


def get_email_verified(id_token: str) -> bool:
    """Return True if the user's email is verified."""
    try:
        data = _firebase_post("lookup", {"idToken": id_token})
        users = data.get("users", [])
        return bool(users and users[0].get("emailVerified", False))
    except Exception:
        return False  # fail closed — transient errors must not grant access


def is_authenticated() -> bool:
    return bool(st.session_state.get("user_uid"))


def current_user() -> dict | None:
    if not is_authenticated():
        return None
    return {
        "uid":          st.session_state.user_uid,
        "email":        st.session_state.user_email,
        "display_name": st.session_state.user_display_name,
    }


def sign_out() -> None:
    for key in ("user_uid", "user_email", "user_display_name",
                "user_id_token", "user_refresh_token"):
        st.session_state.pop(key, None)
    st.session_state.chats = {}
    st.session_state.current_chat_id = None


def _store_user(user: dict) -> None:
    st.session_state.user_uid          = user["uid"]
    st.session_state.user_email        = user["email"]
    st.session_state.user_display_name = user["display_name"]
    st.session_state.user_id_token     = user["id_token"]
    st.session_state.user_refresh_token = user["refresh_token"]


# ── Login UI ───────────────────────────────────────────────────────────────────

_FEATURES = [
    ("Case Chat", "Ask any question — AI answers with citations from your exact documents."),
    ("Timeline", "Auto-structured visual case timelines with category filters."),
    ("Case Board", "Organize documents into named matter workspaces."),
    ("Discussion", "Shared legal forum per case for your entire team."),
]

_TRIAL_STEPS = [
    ("Day 1–2", "Explore the Epstein case — pre-loaded, no upload needed."),
    ("Day 3–4", "Upload 2 of your own closed cases. Verify it on familiar facts."),
    ("Day 5", "Subscribe. Solo from $79/mo · Firm from $149/seat/mo."),
]


def render_login_page() -> bool:
    """Render marketing landing page with login/register. Returns True when authenticated."""
    st.html("""<style>
    [data-testid="stAppViewContainer"] > .main { padding-top: 0 !important; }
    </style>""")

    hero_col, form_col = st.columns([3, 2], gap="large")

    # ── Left: Marketing hero ──────────────────────────────────────────────────
    with hero_col:
        st.html("<div style='height:48px'></div>")
        st.html(
            "<div style='font-size:2.6rem;font-weight:800;color:#0f172a;"
            "letter-spacing:-1.5px;line-height:1.1;margin-bottom:10px'>"
            "Legal research,<br>cited and instant."
            "</div>"
            "<div style='font-size:1rem;color:#475569;margin-bottom:28px;line-height:1.7'>"
            "Atticus is the AI research layer built for lawyers. Upload case files, ask "
            "questions in plain English, get cited answers from your documents in seconds."
            "</div>"
        )

        # Features
        feat_html = "<div style='display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:28px'>"
        for name, desc in _FEATURES:
            feat_html += (
                f"<div style='background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;"
                f"padding:10px 13px'>"
                f"<div style='font-size:0.8rem;font-weight:700;color:#1e293b;margin-bottom:2px'>{name}</div>"
                f"<div style='font-size:0.73rem;color:#64748b;line-height:1.5'>{desc}</div>"
                f"</div>"
            )
        feat_html += "</div>"
        st.html(feat_html)

        # Trial steps
        st.html(
            "<div style='font-size:0.72rem;font-weight:700;color:#94a3b8;"
            "letter-spacing:0.06em;margin-bottom:8px'>HOW THE FREE TRIAL WORKS</div>"
        )
        for step, desc in _TRIAL_STEPS:
            st.html(
                f"<div style='display:flex;gap:10px;align-items:flex-start;margin-bottom:8px'>"
                f"<div style='background:#4f46e5;color:#fff;border-radius:4px;padding:1px 8px;"
                f"font-size:0.68rem;font-weight:700;white-space:nowrap;margin-top:2px'>{step}</div>"
                f"<div style='font-size:0.78rem;color:#475569;line-height:1.5'>{desc}</div>"
                f"</div>"
            )

        st.html(
            "<div style='margin-top:20px;font-size:0.7rem;color:#94a3b8;line-height:1.7'>"
            "Trusted infrastructure: PostgreSQL/pgvector · Anthropic · Firebase · TLS everywhere<br>"
            "GDPR-ready · Data deleted on request · Documents never used to train AI"
            "</div>"
        )

    # ── Right: Auth form ──────────────────────────────────────────────────────
    with form_col:
        st.html("<div style='height:48px'></div>")
        st.html(
            "<div style='background:#fff;border:1px solid #e2e8f0;border-radius:14px;"
            "padding:28px 28px 20px'>"
            "<div style='font-size:1.5rem;font-weight:800;color:#0f172a;"
            "letter-spacing:-0.5px;margin-bottom:2px;font-family:\"Times New Roman\",Times,serif'>Atticus</div>"
            "<div style='font-size:0.78rem;color:#94a3b8;margin-bottom:20px'>Legal Research Intelligence</div>"
            "</div>"
        )

        tab_login, tab_register = st.tabs(["Sign In", "Start Free Trial"])

        with tab_login:
            with st.form("login_form"):
                email    = st.text_input("Email", placeholder="you@lawfirm.com")
                password = st.text_input("Password", type="password")
                submitted = st.form_submit_button("Sign In →", use_container_width=True, type="primary")
                if submitted:
                    if not email or not password:
                        st.error("Please enter your email and password.")
                    else:
                        try:
                            user = sign_in(email, password)
                            _store_user(user)
                            st.rerun()
                        except AuthError as exc:
                            st.error(str(exc))
                        except Exception:
                            st.error("Connection error. Please check your internet and try again.")

            if st.button("Forgot password?", use_container_width=True):
                st.session_state.show_reset = True

            if st.session_state.get("show_reset"):
                reset_email = st.text_input("Enter your email for reset link", key="reset_email_input")
                if st.button("Send reset email", key="send_reset_btn"):
                    try:
                        send_password_reset(reset_email)
                        st.success("Reset email sent — check your inbox.")
                        st.session_state.show_reset = False
                    except AuthError as exc:
                        st.error(str(exc))

        with tab_register:
            with st.form("register_form"):
                r_name  = st.text_input("Full name")
                r_email = st.text_input("Work email", placeholder="you@lawfirm.com", key="reg_email")
                r_pass  = st.text_input("Password (min 8 characters)", type="password", key="reg_pass")
                r_pass2 = st.text_input("Confirm password", type="password")
                accepted = st.checkbox(
                    "I agree to the Terms of Service and Privacy Policy",
                    help="View Terms and Privacy from the Legal page after signing in.",
                )
                submitted = st.form_submit_button(
                    "Start Free Trial →", use_container_width=True, type="primary"
                )
                if submitted:
                    if not all([r_name.strip(), r_email.strip(), r_pass, r_pass2]):
                        st.error("All fields are required.")
                    elif r_pass != r_pass2:
                        st.error("Passwords do not match.")
                    elif len(r_pass) < 8:
                        st.error("Password must be at least 8 characters.")
                    elif not accepted:
                        st.error("You must accept the Terms of Service to continue.")
                    else:
                        try:
                            user = register(r_email.strip(), r_pass, r_name.strip())
                            _store_user(user)
                            send_email_verification(user["id_token"])
                            st.session_state._email_verified = False
                            st.rerun()
                        except AuthError as exc:
                            st.error(str(exc))
                        except Exception:
                            st.error("Connection error. Please check your internet and try again.")

        st.html(
            "<div style='text-align:center;font-size:0.68rem;color:#94a3b8;"
            "margin-top:16px;line-height:1.7'>"
            "AI responses are research aids only — not legal advice.<br>"
            "No attorney-client relationship is created by use of this platform."
            "</div>"
        )

    return is_authenticated()
