"""Terms of Service and Privacy Policy pages."""
from __future__ import annotations

import streamlit as st

_EFFECTIVE_DATE = "June 1, 2026"
_PRODUCT_NAME   = "Atticus"
_COMPANY_NAME   = "Atticus"
_CONTACT_EMAIL  = "legal@atticus.ai"


def _section(title: str, body: str) -> None:
    st.html(
        f"<div style='margin-bottom:18px'>"
        f"<div style='font-size:0.85rem;font-weight:700;color:#1e293b;"
        f"margin-bottom:5px;margin-top:14px'>{title}</div>"
        f"<div style='font-size:0.8rem;color:#475569;line-height:1.75'>{body}</div>"
        f"</div>"
    )


def _render_terms() -> None:
    st.html(
        "<div style='font-size:0.72rem;color:#94a3b8;margin-bottom:20px'>"
        f"Effective date: {_EFFECTIVE_DATE} &nbsp;·&nbsp; "
        f"Questions: <strong>{_CONTACT_EMAIL}</strong>"
        "</div>"
    )

    _section("1. Acceptance of Terms",
        f"By accessing or using {_PRODUCT_NAME} (the \"Service\"), you agree to be bound by "
        f"these Terms of Service. If you do not agree, do not use the Service. "
        f"These terms constitute a binding legal agreement between you and {_COMPANY_NAME} (\"we\", \"us\")."
    )

    _section("2. Service Description",
        f"{_PRODUCT_NAME} is an AI-powered legal research and document analysis platform. "
        "The Service enables users to upload documents, perform semantic searches, generate "
        "AI-assisted summaries, and collaborate on case analysis. <strong>The Service is a "
        "research tool only and does not provide legal advice.</strong>"
    )

    _section("3. No Legal Advice",
        "ALL CONTENT GENERATED BY THE SERVICE — INCLUDING AI-GENERATED SUMMARIES, TIMELINES, "
        "CASE ANALYSES, AND SEARCH RESULTS — CONSTITUTES RESEARCH AIDS ONLY. "
        "Nothing in the Service creates an attorney-client relationship. "
        "AI-generated output must be independently verified by a licensed attorney "
        "before reliance in any legal proceeding, client matter, or professional context. "
        "We expressly disclaim any liability arising from reliance on AI-generated content."
    )

    _section("4. Permitted Use",
        "You may use the Service solely for: (a) lawful legal research and document analysis; "
        "(b) internal law firm or legal department workflows; (c) educational purposes. "
        "You must be at least 18 years old and legally authorized to practice law or conduct "
        "legal research in your jurisdiction, or be supervised by a licensed attorney."
    )

    _section("5. Prohibited Conduct",
        "You may not: (a) use the Service to provide unlicensed legal advice to third parties; "
        "(b) upload documents you do not have the right to share; "
        "(c) attempt to reverse-engineer, scrape, or extract model weights; "
        "(d) use the Service to harass, defame, or harm any individual named in case materials; "
        "(e) circumvent rate limits or access controls; "
        "(f) upload material containing malware, exploits, or malicious code; "
        "(g) share your account credentials with third parties."
    )

    _section("6. User Content",
        "You retain all ownership rights in documents you upload. By uploading content, you grant "
        f"us a limited, non-exclusive license to process, embed, and index your content solely "
        "to provide the Service. We do not use your uploaded documents to train AI models. "
        "You represent that you have all necessary rights and permissions to upload any document."
    )

    _section("7. Subscription and Payment",
        "Access to the Service requires a paid subscription after any applicable free trial. "
        "Subscriptions renew automatically unless cancelled before the renewal date. "
        "Fees are non-refundable except as required by applicable law. "
        "We reserve the right to change pricing with 30 days notice."
    )

    _section("8. Free Trial",
        "New users may access a limited free trial. The trial includes access to pre-loaded case "
        "materials and the ability to upload a limited number of documents. "
        "Trial terms are subject to change. Abuse of free trial access may result in immediate "
        "termination of access."
    )

    _section("9. Intellectual Property",
        f"The Service, including its software, AI models, UI design, and all non-user content, "
        f"is the exclusive property of {_COMPANY_NAME} and is protected by copyright, "
        "trade secret, and other intellectual property laws. "
        "You may not copy, modify, or distribute any part of the Service without prior written consent."
    )

    _section("10. Confidentiality",
        "You acknowledge that uploaded documents and case analyses may contain sensitive legal "
        "information. We implement industry-standard security measures to protect your data. "
        "You are responsible for maintaining appropriate access controls within your organization "
        "and for compliance with any applicable confidentiality obligations to your clients."
    )

    _section("11. Disclaimer of Warranties",
        "THE SERVICE IS PROVIDED \"AS IS\" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, "
        "INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR "
        "NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, "
        "ERROR-FREE, OR THAT AI-GENERATED CONTENT WILL BE ACCURATE OR COMPLETE."
    )

    _section("12. Limitation of Liability",
        f"TO THE MAXIMUM EXTENT PERMITTED BY LAW, {_COMPANY_NAME.upper()} SHALL NOT BE LIABLE "
        "FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, "
        "INCLUDING LOST PROFITS, ARISING FROM YOUR USE OF THE SERVICE. "
        "OUR TOTAL LIABILITY SHALL NOT EXCEED THE AMOUNT PAID BY YOU IN THE 12 MONTHS "
        "PRECEDING THE CLAIM."
    )

    _section("13. Termination",
        "We may suspend or terminate your account at any time for breach of these Terms. "
        "You may cancel your account from the Profile page at any time. "
        "Upon termination, your right to access the Service ceases immediately. "
        "You may request deletion of your data as described in our Privacy Policy."
    )

    _section("14. Governing Law",
        "These Terms are governed by the laws of the State of Delaware, United States, "
        "without regard to conflict of law principles. Any disputes shall be resolved "
        "exclusively in the state or federal courts located in Delaware."
    )

    _section("15. Changes to Terms",
        "We may update these Terms at any time. We will notify you of material changes "
        "via email or an in-app notice. Continued use after notice constitutes acceptance "
        "of the updated Terms."
    )

    st.html(
        f"<div style='font-size:0.72rem;color:#94a3b8;margin-top:24px;padding-top:12px;"
        f"border-top:1px solid #e2e8f0'>Contact: {_CONTACT_EMAIL}</div>"
    )


def _render_privacy() -> None:
    st.html(
        "<div style='font-size:0.72rem;color:#94a3b8;margin-bottom:20px'>"
        f"Effective date: {_EFFECTIVE_DATE} &nbsp;·&nbsp; "
        f"Questions: <strong>{_CONTACT_EMAIL}</strong>"
        "</div>"
    )

    _section("1. Who We Are",
        f"{_COMPANY_NAME} operates {_PRODUCT_NAME}, an AI-powered legal research platform. "
        f"We are the data controller for personal information collected through the Service. "
        f"Contact: {_CONTACT_EMAIL}"
    )

    _section("2. Data We Collect",
        "<strong>Account data:</strong> Email address, display name, encrypted password (managed by Firebase).<br>"
        "<strong>Usage data:</strong> Queries submitted, pages visited, number of documents uploaded, "
        "response lengths, timestamps — stored in our audit log.<br>"
        "<strong>Document data:</strong> PDFs and other files you upload, their extracted text, "
        "and AI-generated embeddings.<br>"
        "<strong>Session data:</strong> Chat history (stored in-session and optionally persisted to our database).<br>"
        "<strong>Technical data:</strong> IP address, browser type, Streamlit session identifiers."
    )

    _section("3. How We Use Your Data",
        "We use your data to: (a) provide and improve the Service; "
        "(b) authenticate your identity and secure your account; "
        "(c) enforce rate limits and prevent abuse; "
        "(d) monitor system performance and diagnose errors; "
        "(e) comply with legal obligations. "
        "We do not sell your data. We do not use your uploaded documents to train AI models."
    )

    _section("4. Third-Party Processors",
        "<strong>Google Firebase</strong> — Authentication, identity management (Google Privacy Policy applies).<br>"
        "<strong>PostgreSQL/pgvector host</strong> — Secure database storing document embeddings and usage logs.<br>"
        "<strong>Anthropic, PBC</strong> — AI language model provider. Queries are sent to Anthropic's API "
        "to generate responses. Anthropic's data processing terms apply.<br>"
        "All processors are bound by data processing agreements and are prohibited from using "
        "your data for their own purposes."
    )

    _section("5. Data Retention",
        "Account data is retained until you delete your account. "
        "Usage logs (query text, timestamps) are retained for 12 months. "
        "Uploaded documents and their embeddings are retained until you delete them from the Data page "
        "or delete your account. "
        "Deleted data is purged from all systems within 30 days."
    )

    _section("6. Your Rights (GDPR / CCPA)",
        "<strong>Access:</strong> Request a copy of your personal data.<br>"
        "<strong>Rectification:</strong> Correct inaccurate data via your Profile page.<br>"
        "<strong>Erasure:</strong> Delete all your data from Profile → Danger Zone → Delete all my data.<br>"
        "<strong>Portability:</strong> Export your chat history via the Export button on each chat.<br>"
        "<strong>Objection:</strong> Object to processing by contacting us at the email above.<br>"
        "California residents may exercise additional rights under CCPA by contacting us."
    )

    _section("7. Security",
        "We implement technical and organizational measures to protect your data, including: "
        "TLS encryption in transit, database encryption at rest, "
        "Firebase's industry-standard authentication security, "
        "role-based access controls, and regular security reviews. "
        "No system is 100% secure. If you suspect a breach, contact us immediately."
    )

    _section("8. Cookies and Tracking",
        "The Service uses Streamlit's session cookies solely to maintain your authenticated session. "
        "We do not use advertising cookies, tracking pixels, or third-party analytics beyond "
        "those inherent to the infrastructure providers listed above."
    )

    _section("9. Children's Privacy",
        "The Service is not directed to individuals under the age of 18. "
        "We do not knowingly collect personal information from minors. "
        "If you believe a minor has created an account, contact us for immediate deletion."
    )

    _section("10. Changes to This Policy",
        "We may update this Privacy Policy periodically. "
        "We will notify you of material changes via email or in-app notice. "
        "The date at the top of this page reflects the most recent update."
    )

    st.html(
        f"<div style='font-size:0.72rem;color:#94a3b8;margin-top:24px;padding-top:12px;"
        f"border-top:1px solid #e2e8f0'>Data Protection Contact: {_CONTACT_EMAIL}</div>"
    )


def render_legal_page(initial_tab: str = "terms", pre_auth: bool = False) -> None:
    if pre_auth:
        st.html("""<style>
        [data-testid="stSidebar"] { display: none !important; }
        footer { display: none !important; }
        #MainMenu { display: none !important; }
        header[data-testid="stHeader"] { display: none !important; }
        </style>""")
        nc1, _, nc2 = st.columns([2, 5, 1])
        with nc1:
            st.html(
                "<div style='padding:16px 0 12px 8px;display:flex;align-items:center;gap:7px'>"
                "<div style='width:16px;height:16px;background:linear-gradient(135deg,#6366f1,#8b5cf6);"
                "border-radius:3px;flex-shrink:0'></div>"
                "<span style='font-size:1.1rem;font-weight:700;color:#0f172a;letter-spacing:-0.3px'>Atticus</span>"
                "</div>"
            )
        with nc2:
            if st.button("Home", key="legal_back_home", use_container_width=True):
                st.session_state.pre_auth_page = "landing"
                st.rerun()
        st.html("<div style='height:1px;background:#e2e8f0;margin-bottom:8px'></div>")

    st.html(
        "<div style='padding:16px 0 4px'>"
        "<span style='font-size:1.4rem;font-weight:700;color:#1e293b'>Legal</span>"
        "</div>"
    )

    tab_terms, tab_privacy = st.tabs(["Terms of Service", "Privacy Policy"])

    with tab_terms:
        st.html(
            "<div style='font-size:1rem;font-weight:600;color:#1e293b;margin-bottom:4px'>"
            f"Terms of Service — {_PRODUCT_NAME}</div>"
        )
        _render_terms()

    with tab_privacy:
        st.html(
            "<div style='font-size:1rem;font-weight:600;color:#1e293b;margin-bottom:4px'>"
            f"Privacy Policy — {_PRODUCT_NAME}</div>"
        )
        _render_privacy()
